### PR TITLE
Log/counter

### PR DESCRIPTION
**Pull request by gi8lino**
new method to count errors

### CODE REVIEW

**Comment by rxbn** [comment]
LGTM but the version isn't semver compliant. Since we are not changing any "user-facing" parts and only the program logic, a new release isn't really necessary at all. In case it fixes a user noticeable bug, only a 0.0.x increase would be adequate.

**Review by rxbn — CHANGES_REQUESTED** [review]
see previous comment

**Comment by gi8lino** [comment]
> LGTM but the version isn't semver compliant. Since we are not changing any "user-facing" parts and only the program logic, a new release isn't really necessary at all. In case it fixes a user noticeable bug, only a 0.0.x increase would be adequate.

I agree and also changed the version to a fix. Please check again.

**Review by rxbn — APPROVED** [review]
LGTM

**Pull request merged**
